-- AlterTable
ALTER TABLE `cafes` ADD COLUMN `since` VARCHAR(191) NOT NULL DEFAULT '';

-- AlterTable
ALTER TABLE `themes` ADD COLUMN `genre` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `lockingRatio` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `price` INTEGER NOT NULL DEFAULT 0;
