FROM python:3.9-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt
COPY ./.env* /code/

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./prisma /code/prisma
COPY ./app /code/app

RUN prisma generate

ENV APP_ENV=production

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]